//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco01.MDC.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuadreDiario
    {
        public int ID { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto_Inicio { get; set; }
        public Nullable<decimal> Monto_Fin { get; set; }
    }
}
