//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco01.MDC.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositoDatos
    {
        public string Benefactor { get; set; }
        public string Especificaciones { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public int ID { get; set; }
        public string Nro_de_Cuenta { get; set; }
    }
}
