//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco01.MDC.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialTransacciones
    {
        public int ID { get; set; }
        public int IDCajero { get; set; }
        public int IDCuadre { get; set; }
        public string Tipo { get; set; }
        public decimal Monto { get; set; }
    }
}
