//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco01.MDC.Resources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MDC_LocalDBEntities : DbContext
    {
        public MDC_LocalDBEntities()
            : base("name=MDC_LocalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cajeros> Cajeros { get; set; }
        public virtual DbSet<CuadreDiario> CuadreDiario { get; set; }
        public virtual DbSet<DepositoDatos> DepositoDatos { get; set; }
        public virtual DbSet<HistorialTransacciones> HistorialTransacciones { get; set; }
    
        public virtual ObjectResult<ValidaCajero_Result> ValidaCajero(string user, string passwd)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passwdParameter = passwd != null ?
                new ObjectParameter("passwd", passwd) :
                new ObjectParameter("passwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidaCajero_Result>("ValidaCajero", userParameter, passwdParameter);
        }
    
        public virtual ObjectResult<GetCajero_Result> GetCajero(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCajero_Result>("GetCajero", usuarioParameter);
        }
    
        public virtual ObjectResult<string> GetSucursales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetSucursales");
        }
    }
}
